name: Deploy to Render

on:
  push:
    branches:
      - main # Chạy tự động mỗi khi bạn push code vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước này dùng để "gọi" Render bắt đầu deploy
      - name: Deploy to Render
        run: |
          curl -f ${{ secrets.RENDER_DEPLOY_HOOK_URL }}